export const paths = {
  HOME: 'home',
  ONBOARDING: 'onboarding',
  LOGIN: 'login',
  SIGNUP: 'signup',
  SPLASH: 'splash',
  USERPROFILES: 'user-profiles',
  BOTTOMNAVIGATOR: 'bottom-navigator',
  DRAWERNAVIGATOR: 'drawer-navigator',
  DOWNLOADS: 'downloads',
  SEARCH: 'search',
  DISCOVER: 'discover',
  PROFILE: 'profile',
  HOMESTACK: 'home-stack',
  SEARCHSTACK: 'search-stack',
  DISCOVERSTACK: 'discover-stack',
  DOWNLOADSSTACK: 'download-stack',
  PROFILESTACK: 'profile-stack',
  MOVIEDETAILS: 'movie-details',
  MOVIES: 'movies',
  CATEGORIES: 'categories',
  MYLIST: 'my-list',
  FAVORITES: 'favorites',
  HELP: 'help',
  MUSIC: 'music'
};
